### ISSUE TITLE
Missing semi-colon at end of minified version.

### ISSUE THREAD

**Issue by vdswouter** [fat/bean#117]
When I make build of projects, my gulp minifies and concats all the script files into one .js file.
Bean.min.js has no semicolon at the end of the file causing errors in the script that is concatted after it.

**Comment by rvagg** [comment]
@ded what's our stance on this these days? are we just caving in and adding semicolons or standing our ground that this is a build-tool problem?

**Comment by ded** [comment]
add it. it's honestly not even worth the hassle of each PR that adds it.

**Comment by rvagg** [comment]
fine, will accept a PR for this then @vdswouter

**Comment by vdswouter** [comment]
I'm fairly new to opensource coding.

**Comment by vdswouter** [comment]
I'm fairly new to opensource coding. Sorry for being a noob but you have to start somewhere... ;-)
I suppose I can't just make a PR with a added semi-colon in the minified build because it will be overwritten. I think it is removed by the uglify script but i have no clue on how to fix this.
