### ISSUE TITLE
No valid bower.json was found in any branch or tag of https://github.com/fat/bean.git

### ISSUE THREAD

**Issue by videni** [fat/bean#130]
```
No valid bower.json was found in any branch or tag of https://github.com/fat/bean.git, could not    load a package from it.
```
I  created a issue here , but found no solution   https://github.com/orocrm/platform/issues/669

**Comment by dev7ch** [comment]
could be a solution as well: 

https://stackoverflow.com/questions/35159635/php-and-composer-with-docker-build-failed-to-clone-git

**Comment by Dorbah** [comment]
Updating antivirus program Kaspersky Free helps me to solve the problem, because of it blocks SSL2
